# Generated by Django 4.1.3 on 2022-12-31 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0002_proveedor_remove_tarea_cantidad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarea',
            name='ficha_tecnica',
        ),
        migrations.AddField(
            model_name='tarea',
            name='cantidad',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
