# Generated by Django 4.1.3 on 2022-12-31 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0003_remove_tarea_ficha_tecnica_tarea_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='modelo',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='modelos', to='tareas.producto'),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='proveedor',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='tareas.proveedor'),
        ),
    ]
