# Generated by Django 4.1.3 on 2022-12-31 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0004_alter_tarea_modelo_alter_tarea_proveedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='modelo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modelos', to='tareas.producto'),
        ),
    ]
