# Generated by Django 4.1.3 on 2022-12-31 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0009_alter_tarea_modelo_alter_tarea_proveedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='cantidad',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
