# Generated by Django 4.1.3 on 2023-01-01 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0012_producto_cantidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='cantidad',
        ),
    ]
