# Generated by Django 4.1.3 on 2023-02-07 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0014_alter_imagentarea_imagen_alter_imagentarea_tarea_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarea',
            name='imagen',
        ),
        migrations.AddField(
            model_name='tarea',
            name='imagen',
            field=models.FileField(null=True, upload_to='Chimeneas'),
        ),
    ]
