# Generated by Django 4.1.3 on 2023-02-09 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0017_producto_cantidad_alter_tarea_cantidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='cantidad',
        ),
        migrations.AlterField(
            model_name='tarea',
            name='cantidad',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
