# Generated by Django 4.1.3 on 2023-02-09 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0018_remove_producto_cantidad_alter_tarea_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='cantidad',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='cantidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cantida', to='tareas.producto'),
        ),
    ]
