# Generated by Django 4.1.3 on 2023-02-09 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0019_producto_cantidad_alter_tarea_cantidad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='cantidad',
            new_name='cantidades',
        ),
        migrations.RemoveField(
            model_name='tarea',
            name='cantidad',
        ),
        migrations.AddField(
            model_name='tarea',
            name='cantidades',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cantidad', to='tareas.producto'),
        ),
    ]
