# Generated by Django 4.1.3 on 2023-02-09 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0020_rename_cantidad_producto_cantidades_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='cantidades',
            new_name='cantidad',
        ),
        migrations.RemoveField(
            model_name='tarea',
            name='cantidades',
        ),
        migrations.AddField(
            model_name='tarea',
            name='cantidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cantidades', to='tareas.producto'),
        ),
    ]
