# Generated by Django 4.1.3 on 2023-02-09 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0021_rename_cantidades_producto_cantidad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='cantidad',
        ),
        migrations.AlterField(
            model_name='tarea',
            name='cantidad',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
