# Generated by Django 4.1.3 on 2023-02-10 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0023_remove_tarea_modelo_tarea_modelo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarea',
            name='modelo',
        ),
        migrations.AddField(
            model_name='tarea',
            name='modelo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tareas.producto'),
        ),
    ]
