# Generated by Django 4.1.3 on 2023-02-12 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0024_remove_tarea_modelo_tarea_modelo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='cantidad',
            field=models.IntegerField(null=True),
        ),
    ]
