# Generated by Django 4.1.3 on 2023-02-12 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0025_alter_tarea_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='cantidad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='modelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tareas.producto'),
        ),
    ]
