# Generated by Django 4.1.3 on 2023-02-12 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0026_alter_tarea_cantidad_alter_tarea_modelo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Montajes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=25)),
                ('cantidad', models.IntegerField()),
            ],
        ),
    ]
