# Generated by Django 4.1.3 on 2023-02-12 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0027_montajes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Montajes',
        ),
    ]
