# Generated by Django 4.1.3 on 2023-03-23 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0035_visitas_dirección_visitas_telefono'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitas',
            old_name='dirección',
            new_name='direccion',
        ),
    ]
