# Generated by Django 4.1.3 on 2023-03-24 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0036_rename_dirección_visitas_direccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitas',
            name='creacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
