# Generated by Django 4.1.3 on 2023-03-25 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0038_rename_creacion_visitas_visita'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitas',
            old_name='cliente',
            new_name='apellidos',
        ),
        migrations.RenameField(
            model_name='visitas',
            old_name='descripcion',
            new_name='nombre',
        ),
    ]
