# Generated by Django 4.1.3 on 2023-03-26 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0039_rename_cliente_visitas_apellidos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitas',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
