# Generated by Django 4.1.3 on 2023-04-01 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0041_rename_url_visitas_ubicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='imagen',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
