# Generated by Django 4.1.3 on 2023-04-01 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0042_tarea_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarea',
            name='imagen',
        ),
    ]
